// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_InputGain;
lv_obj_t * ui_InputGain = NULL;
// event funtions

// build funtions

void ui_InputGain_screen_init(void)
{
    ui_InputGain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InputGain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_InputGain = ui_InputGain;

}

void ui_InputGain_screen_destroy(void)
{
    if(ui_InputGain) lv_obj_del(ui_InputGain);

    // NULL screen variables
    uic_InputGain = NULL;
    ui_InputGain = NULL;

}
