// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Menu;
lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenEffects, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenEffects_screen_init);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button6, 155);
    lv_obj_set_height(ui_Button6, 110);
    lv_obj_set_x(ui_Button6, -80);
    lv_obj_set_y(ui_Button6, -60);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button6, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Effects");

    ui_Button1 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button1, 155);
    lv_obj_set_height(ui_Button1, 110);
    lv_obj_set_x(ui_Button1, 80);
    lv_obj_set_y(ui_Button1, -60);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Input Gain");

    ui_Button2 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button2, 155);
    lv_obj_set_height(ui_Button2, 110);
    lv_obj_set_x(ui_Button2, -80);
    lv_obj_set_y(ui_Button2, 55);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button2, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Output Level");

    ui_Button3 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button3, 155);
    lv_obj_set_height(ui_Button3, 110);
    lv_obj_set_x(ui_Button3, 80);
    lv_obj_set_y(ui_Button3, 55);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "System");

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    uic_Menu = ui_Menu;

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    uic_Menu = NULL;
    ui_Menu = NULL;
    ui_Button6 = NULL;
    ui_Label3 = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_Button2 = NULL;
    ui_Label4 = NULL;
    ui_Button3 = NULL;
    ui_Label5 = NULL;

}
