// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern lv_obj_t * ui_Menu;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Menu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

