// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_OutputLevel;
lv_obj_t * ui_OutputLevel = NULL;
// event funtions

// build funtions

void ui_OutputLevel_screen_init(void)
{
    ui_OutputLevel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OutputLevel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_OutputLevel = ui_OutputLevel;

}

void ui_OutputLevel_screen_destroy(void)
{
    if(ui_OutputLevel) lv_obj_del(ui_OutputLevel);

    // NULL screen variables
    uic_OutputLevel = NULL;
    ui_OutputLevel = NULL;

}
