// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OUTPUTLEVEL_H
#define UI_OUTPUTLEVEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OutputLevel
extern void ui_OutputLevel_screen_init(void);
extern void ui_OutputLevel_screen_destroy(void);
extern lv_obj_t * ui_OutputLevel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_OutputLevel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

