// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_System;
lv_obj_t * ui_System = NULL;
// event funtions

// build funtions

void ui_System_screen_init(void)
{
    ui_System = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_System, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_System = ui_System;

}

void ui_System_screen_destroy(void)
{
    if(ui_System) lv_obj_del(ui_System);

    // NULL screen variables
    uic_System = NULL;
    ui_System = NULL;

}
