// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SYSTEM_H
#define UI_SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_System
extern void ui_System_screen_init(void);
extern void ui_System_screen_destroy(void);
extern lv_obj_t * ui_System;
// CUSTOM VARIABLES
extern lv_obj_t * uic_System;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

