// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENEFFECTS_H
#define UI_SCREENEFFECTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenEffects
extern void ui_ScreenEffects_screen_init(void);
extern void ui_ScreenEffects_screen_destroy(void);
extern lv_obj_t * ui_ScreenEffects;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenEffects;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

