// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_ScreenEffects;
lv_obj_t * ui_ScreenEffects = NULL;
// event funtions

// build funtions

void ui_ScreenEffects_screen_init(void)
{
    ui_ScreenEffects = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEffects, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_ScreenEffects = ui_ScreenEffects;

}

void ui_ScreenEffects_screen_destroy(void)
{
    if(ui_ScreenEffects) lv_obj_del(ui_ScreenEffects);

    // NULL screen variables
    uic_ScreenEffects = NULL;
    ui_ScreenEffects = NULL;

}
