// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_DifferentEffects = NULL;
lv_obj_t * ui_PanelEffects = NULL;
lv_obj_t * ui_LabelEffectsTitle = NULL;
lv_obj_t * ui_BtnEffectsBack = NULL;
lv_obj_t * ui_BlockDelay = NULL;
lv_obj_t * ui_BtnDelayIcon = NULL;
lv_obj_t * ui_LabelDelay = NULL;
lv_obj_t * ui_LabelEffect02 = NULL;
lv_obj_t * ui_SwitchDelayToggle = NULL;
lv_obj_t * ui_BlockReverb = NULL;
lv_obj_t * ui_BtnReverbIcon = NULL;
lv_obj_t * ui_LabelEffect01 = NULL;
lv_obj_t * ui_LabelReverb = NULL;
lv_obj_t * ui_SwitchReverbToggle = NULL;
lv_obj_t * ui_BlockCompressor = NULL;
lv_obj_t * ui_BtnCompressorIcon = NULL;
lv_obj_t * ui_LabelComp = NULL;
lv_obj_t * ui_LabelEffect04 = NULL;
lv_obj_t * ui_SwitchCompressorToggle = NULL;
lv_obj_t * ui_BlockDistortion = NULL;
lv_obj_t * ui_BtnDistortionIcon = NULL;
lv_obj_t * ui_LabelDistortion = NULL;
lv_obj_t * ui_SwitchDistortionToggle = NULL;
lv_obj_t * ui_LabelEffect03 = NULL;
lv_obj_t * ui_BlockChorus = NULL;
lv_obj_t * ui_BtnChorusIcon = NULL;
lv_obj_t * ui_LabelChorus = NULL;
lv_obj_t * ui_LabelEffect05 = NULL;
lv_obj_t * ui_SwitchChorusToggle = NULL;
lv_obj_t * ui_BlockCab = NULL;
lv_obj_t * ui_BtnCabIcon = NULL;
lv_obj_t * ui_SwitchCabToggle = NULL;
lv_obj_t * ui_LabelCABIR = NULL;
lv_obj_t * ui_LabelEffect06 = NULL;
lv_obj_t * ui_BlockAmp = NULL;
lv_obj_t * ui_BtnAmpIcon = NULL;
lv_obj_t * ui_SwitchAmpToggle = NULL;
lv_obj_t * ui_LabelAmp = NULL;
lv_obj_t * ui_LabelEffect07 = NULL;
lv_obj_t * ui_BlockEQ = NULL;
lv_obj_t * ui_BtnEQIcon = NULL;
lv_obj_t * ui_LabelEQ = NULL;
lv_obj_t * ui_LabelEffect08 = NULL;
lv_obj_t * ui_SwitchEQToggle = NULL;
lv_obj_t * ui_PanelEffectSelector = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_BtnActionEdit = NULL;
lv_obj_t * ui_Cha = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_BtnActionReplace = NULL;
lv_obj_t * ui_Cha1 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
// event funtions
void ui_event_BtnEffectsBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_TitleMenuHeader, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TitleMenuHeader_screen_init);
    }
}

void ui_event_BtnDelayIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnReverbIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnCompressorIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnDistortionIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnChorusIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnCabIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnAmpIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnEQIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectActiveSlot(e);
    }
}

void ui_event_BtnActionEdit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnBtnEditParamsClicked(e);
    }
}

void ui_event_BtnActionReplace(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnBtnReplaceClicked(e);
    }
}

// build funtions

void ui_DifferentEffects_screen_init(void)
{
    ui_DifferentEffects = lv_obj_create(NULL);
    lv_obj_add_flag(ui_DifferentEffects, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_bg_color(ui_DifferentEffects, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DifferentEffects, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEffects = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_PanelEffects, lv_pct(100));
    lv_obj_set_height(ui_PanelEffects, lv_pct(20));
    lv_obj_set_x(ui_PanelEffects, lv_pct(0));
    lv_obj_set_y(ui_PanelEffects, lv_pct(-40));
    lv_obj_set_align(ui_PanelEffects, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEffects, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelEffects, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelEffects, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelEffects, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffectsTitle = lv_label_create(ui_PanelEffects);
    lv_obj_set_width(ui_LabelEffectsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffectsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEffectsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffectsTitle, "Effects");

    ui_BtnEffectsBack = lv_imgbtn_create(ui_DifferentEffects);
    lv_imgbtn_set_src(ui_BtnEffectsBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnEffectsBack, 30);
    lv_obj_set_height(ui_BtnEffectsBack, 40);
    lv_obj_set_x(ui_BtnEffectsBack, -139);
    lv_obj_set_y(ui_BtnEffectsBack, -93);
    lv_obj_set_align(ui_BtnEffectsBack, LV_ALIGN_CENTER);

    ui_BlockDelay = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockDelay, 60);
    lv_obj_set_height(ui_BlockDelay, 60);
    lv_obj_set_x(ui_BlockDelay, -40);
    lv_obj_set_y(ui_BlockDelay, -15);
    lv_obj_set_align(ui_BlockDelay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockDelay, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockDelay, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockDelay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockDelay, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockDelay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDelayIcon = lv_imgbtn_create(ui_BlockDelay);
    lv_imgbtn_set_src(ui_BtnDelayIcon, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnDelayIcon, 60);
    lv_obj_set_height(ui_BtnDelayIcon, 60);
    lv_obj_set_align(ui_BtnDelayIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnDelayIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnDelayIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnDelayIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnDelayIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnDelayIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelDelay = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelDelay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDelay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDelay, -40);
    lv_obj_set_y(ui_LabelDelay, 25);
    lv_obj_set_align(ui_LabelDelay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDelay, "-");
    lv_obj_set_style_text_color(ui_LabelDelay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDelay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect02 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect02, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect02, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect02, -40);
    lv_obj_set_y(ui_LabelEffect02, -60);
    lv_obj_set_align(ui_LabelEffect02, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect02, "Effect 2");
    lv_obj_set_style_text_color(ui_LabelEffect02, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchDelayToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchDelayToggle, 50);
    lv_obj_set_height(ui_SwitchDelayToggle, 25);
    lv_obj_set_x(ui_SwitchDelayToggle, -40);
    lv_obj_set_y(ui_SwitchDelayToggle, 50);
    lv_obj_set_align(ui_SwitchDelayToggle, LV_ALIGN_CENTER);

    ui_BlockReverb = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockReverb, 60);
    lv_obj_set_height(ui_BlockReverb, 60);
    lv_obj_set_x(ui_BlockReverb, -120);
    lv_obj_set_y(ui_BlockReverb, -15);
    lv_obj_set_align(ui_BlockReverb, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockReverb, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockReverb, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockReverb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockReverb, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockReverb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnReverbIcon = lv_imgbtn_create(ui_BlockReverb);
    lv_imgbtn_set_src(ui_BtnReverbIcon, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnReverbIcon, 60);
    lv_obj_set_height(ui_BtnReverbIcon, 60);
    lv_obj_set_x(ui_BtnReverbIcon, 0);
    lv_obj_set_y(ui_BtnReverbIcon, 1);
    lv_obj_set_align(ui_BtnReverbIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnReverbIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnReverbIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnReverbIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnReverbIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnReverbIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelEffect01 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect01, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect01, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect01, -120);
    lv_obj_set_y(ui_LabelEffect01, -60);
    lv_obj_set_align(ui_LabelEffect01, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect01, "Effect 1");
    lv_obj_set_style_text_color(ui_LabelEffect01, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReverb = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelReverb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReverb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelReverb, -120);
    lv_obj_set_y(ui_LabelReverb, 25);
    lv_obj_set_align(ui_LabelReverb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReverb, "-");
    lv_obj_set_style_text_color(ui_LabelReverb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReverb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchReverbToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchReverbToggle, 50);
    lv_obj_set_height(ui_SwitchReverbToggle, 25);
    lv_obj_set_x(ui_SwitchReverbToggle, -120);
    lv_obj_set_y(ui_SwitchReverbToggle, 50);
    lv_obj_set_align(ui_SwitchReverbToggle, LV_ALIGN_CENTER);

    ui_BlockCompressor = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockCompressor, 60);
    lv_obj_set_height(ui_BlockCompressor, 60);
    lv_obj_set_x(ui_BlockCompressor, 120);
    lv_obj_set_y(ui_BlockCompressor, -15);
    lv_obj_set_align(ui_BlockCompressor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockCompressor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockCompressor, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockCompressor, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockCompressor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockCompressor, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockCompressor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCompressorIcon = lv_imgbtn_create(ui_BlockCompressor);
    lv_imgbtn_set_src(ui_BtnCompressorIcon, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnCompressorIcon, 60);
    lv_obj_set_height(ui_BtnCompressorIcon, 60);
    lv_obj_set_align(ui_BtnCompressorIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCompressorIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnCompressorIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnCompressorIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnCompressorIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnCompressorIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelComp = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelComp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelComp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelComp, 120);
    lv_obj_set_y(ui_LabelComp, 25);
    lv_obj_set_align(ui_LabelComp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelComp, "-");
    lv_obj_set_style_text_color(ui_LabelComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect04 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect04, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect04, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect04, 120);
    lv_obj_set_y(ui_LabelEffect04, -60);
    lv_obj_set_align(ui_LabelEffect04, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect04, "Effect 4");
    lv_obj_set_style_text_color(ui_LabelEffect04, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect04, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchCompressorToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchCompressorToggle, 50);
    lv_obj_set_height(ui_SwitchCompressorToggle, 25);
    lv_obj_set_x(ui_SwitchCompressorToggle, 120);
    lv_obj_set_y(ui_SwitchCompressorToggle, 50);
    lv_obj_set_align(ui_SwitchCompressorToggle, LV_ALIGN_CENTER);

    ui_BlockDistortion = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockDistortion, 60);
    lv_obj_set_height(ui_BlockDistortion, 60);
    lv_obj_set_x(ui_BlockDistortion, 40);
    lv_obj_set_y(ui_BlockDistortion, -15);
    lv_obj_set_align(ui_BlockDistortion, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockDistortion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockDistortion, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockDistortion, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockDistortion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockDistortion, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockDistortion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDistortionIcon = lv_imgbtn_create(ui_BlockDistortion);
    lv_imgbtn_set_src(ui_BtnDistortionIcon, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnDistortionIcon, 60);
    lv_obj_set_height(ui_BtnDistortionIcon, 60);
    lv_obj_set_align(ui_BtnDistortionIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnDistortionIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnDistortionIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnDistortionIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnDistortionIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnDistortionIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelDistortion = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelDistortion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDistortion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDistortion, 40);
    lv_obj_set_y(ui_LabelDistortion, 25);
    lv_obj_set_align(ui_LabelDistortion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDistortion, "-");
    lv_obj_set_style_text_color(ui_LabelDistortion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDistortion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchDistortionToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchDistortionToggle, 50);
    lv_obj_set_height(ui_SwitchDistortionToggle, 25);
    lv_obj_set_x(ui_SwitchDistortionToggle, 40);
    lv_obj_set_y(ui_SwitchDistortionToggle, 50);
    lv_obj_set_align(ui_SwitchDistortionToggle, LV_ALIGN_CENTER);

    ui_LabelEffect03 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect03, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect03, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect03, 40);
    lv_obj_set_y(ui_LabelEffect03, -60);
    lv_obj_set_align(ui_LabelEffect03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect03, "Effect 3");
    lv_obj_set_style_text_color(ui_LabelEffect03, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect03, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlockChorus = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockChorus, 60);
    lv_obj_set_height(ui_BlockChorus, 60);
    lv_obj_set_x(ui_BlockChorus, -120);
    lv_obj_set_y(ui_BlockChorus, 180);
    lv_obj_set_align(ui_BlockChorus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockChorus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockChorus, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockChorus, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockChorus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockChorus, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockChorus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnChorusIcon = lv_imgbtn_create(ui_BlockChorus);
    lv_imgbtn_set_src(ui_BtnChorusIcon, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnChorusIcon, 60);
    lv_obj_set_height(ui_BtnChorusIcon, 60);
    lv_obj_set_align(ui_BtnChorusIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnChorusIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnChorusIcon, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnChorusIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnChorusIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnChorusIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnChorusIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelChorus = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelChorus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChorus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChorus, -120);
    lv_obj_set_y(ui_LabelChorus, 220);
    lv_obj_set_align(ui_LabelChorus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChorus, "-");
    lv_obj_set_style_text_color(ui_LabelChorus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChorus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect05 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect05, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect05, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect05, -120);
    lv_obj_set_y(ui_LabelEffect05, 135);
    lv_obj_set_align(ui_LabelEffect05, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect05, "Effect 5");
    lv_obj_set_style_text_color(ui_LabelEffect05, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchChorusToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchChorusToggle, 50);
    lv_obj_set_height(ui_SwitchChorusToggle, 25);
    lv_obj_set_x(ui_SwitchChorusToggle, -120);
    lv_obj_set_y(ui_SwitchChorusToggle, 245);
    lv_obj_set_align(ui_SwitchChorusToggle, LV_ALIGN_CENTER);

    ui_BlockCab = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockCab, 60);
    lv_obj_set_height(ui_BlockCab, 60);
    lv_obj_set_x(ui_BlockCab, -40);
    lv_obj_set_y(ui_BlockCab, 180);
    lv_obj_set_align(ui_BlockCab, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockCab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockCab, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockCab, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockCab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockCab, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockCab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCabIcon = lv_imgbtn_create(ui_BlockCab);
    lv_imgbtn_set_src(ui_BtnCabIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png,
                      NULL);
    lv_obj_set_width(ui_BtnCabIcon, 60);
    lv_obj_set_height(ui_BtnCabIcon, 60);
    lv_obj_set_align(ui_BtnCabIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCabIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnCabIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnCabIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnCabIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnCabIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SwitchCabToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchCabToggle, 50);
    lv_obj_set_height(ui_SwitchCabToggle, 25);
    lv_obj_set_x(ui_SwitchCabToggle, -40);
    lv_obj_set_y(ui_SwitchCabToggle, 245);
    lv_obj_set_align(ui_SwitchCabToggle, LV_ALIGN_CENTER);

    ui_LabelCABIR = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelCABIR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCABIR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCABIR, -40);
    lv_obj_set_y(ui_LabelCABIR, 220);
    lv_obj_set_align(ui_LabelCABIR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCABIR, "-");
    lv_obj_set_style_text_color(ui_LabelCABIR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCABIR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect06 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect06, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect06, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect06, -40);
    lv_obj_set_y(ui_LabelEffect06, 135);
    lv_obj_set_align(ui_LabelEffect06, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect06, "Effect 6");
    lv_obj_set_style_text_color(ui_LabelEffect06, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect06, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlockAmp = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockAmp, 60);
    lv_obj_set_height(ui_BlockAmp, 60);
    lv_obj_set_x(ui_BlockAmp, 40);
    lv_obj_set_y(ui_BlockAmp, 180);
    lv_obj_set_align(ui_BlockAmp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockAmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockAmp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockAmp, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockAmp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockAmp, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockAmp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAmpIcon = lv_imgbtn_create(ui_BlockAmp);
    lv_imgbtn_set_src(ui_BtnAmpIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png,
                      NULL);
    lv_obj_set_width(ui_BtnAmpIcon, 60);
    lv_obj_set_height(ui_BtnAmpIcon, 60);
    lv_obj_set_align(ui_BtnAmpIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnAmpIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnAmpIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BtnAmpIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnAmpIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnAmpIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SwitchAmpToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchAmpToggle, 50);
    lv_obj_set_height(ui_SwitchAmpToggle, 25);
    lv_obj_set_x(ui_SwitchAmpToggle, 40);
    lv_obj_set_y(ui_SwitchAmpToggle, 245);
    lv_obj_set_align(ui_SwitchAmpToggle, LV_ALIGN_CENTER);

    ui_LabelAmp = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelAmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAmp, 40);
    lv_obj_set_y(ui_LabelAmp, 220);
    lv_obj_set_align(ui_LabelAmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAmp, "-");
    lv_obj_set_style_text_color(ui_LabelAmp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAmp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect07 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect07, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect07, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect07, 40);
    lv_obj_set_y(ui_LabelEffect07, 135);
    lv_obj_set_align(ui_LabelEffect07, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect07, "Effect 7");
    lv_obj_set_style_text_color(ui_LabelEffect07, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect07, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlockEQ = lv_obj_create(ui_DifferentEffects);
    lv_obj_set_width(ui_BlockEQ, 60);
    lv_obj_set_height(ui_BlockEQ, 60);
    lv_obj_set_x(ui_BlockEQ, 120);
    lv_obj_set_y(ui_BlockEQ, 180);
    lv_obj_set_align(ui_BlockEQ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlockEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlockEQ, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlockEQ, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlockEQ, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlockEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnEQIcon = lv_imgbtn_create(ui_BlockEQ);
    lv_imgbtn_set_src(ui_BtnEQIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_60dp_ffffff_fill0_wght400_grad0_opsz48_png,
                      NULL);
    lv_obj_set_width(ui_BtnEQIcon, 60);
    lv_obj_set_height(ui_BtnEQIcon, 60);
    lv_obj_set_align(ui_BtnEQIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnEQIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BtnEQIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnEQIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BtnEQIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BtnEQIcon, 10, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelEQ = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEQ, 120);
    lv_obj_set_y(ui_LabelEQ, 220);
    lv_obj_set_align(ui_LabelEQ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEQ, "-");
    lv_obj_set_style_text_color(ui_LabelEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEffect08 = lv_label_create(ui_DifferentEffects);
    lv_obj_set_width(ui_LabelEffect08, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEffect08, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEffect08, 120);
    lv_obj_set_y(ui_LabelEffect08, 135);
    lv_obj_set_align(ui_LabelEffect08, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEffect08, "Effect 8");
    lv_obj_set_style_text_color(ui_LabelEffect08, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEffect08, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchEQToggle = lv_switch_create(ui_DifferentEffects);
    lv_obj_set_width(ui_SwitchEQToggle, 50);
    lv_obj_set_height(ui_SwitchEQToggle, 25);
    lv_obj_set_x(ui_SwitchEQToggle, 120);
    lv_obj_set_y(ui_SwitchEQToggle, 245);
    lv_obj_set_align(ui_SwitchEQToggle, LV_ALIGN_CENTER);

    ui_PanelEffectSelector = lv_roller_create(ui_DifferentEffects);
    lv_roller_set_options(ui_PanelEffectSelector, "Reverb\nDelay\nDistortion\nComp\nChorus \nAmplifier\nEQ\nCancel\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_PanelEffectSelector, 100);
    lv_obj_set_width(ui_PanelEffectSelector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PanelEffectSelector, -1);
    lv_obj_set_y(ui_PanelEffectSelector, 55);
    lv_obj_set_align(ui_PanelEffectSelector, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelEffectSelector, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Container2 = lv_obj_create(ui_DifferentEffects);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 181);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, -68);
    lv_obj_set_y(ui_Container2, 100);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x00D1FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BtnActionEdit = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_BtnActionEdit, 133);
    lv_obj_set_height(ui_BtnActionEdit, 44);
    lv_obj_set_x(ui_BtnActionEdit, 77);
    lv_obj_set_y(ui_BtnActionEdit, 58);
    lv_obj_set_align(ui_BtnActionEdit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnActionEdit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnActionEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnActionEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnActionEdit, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnActionEdit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnActionEdit, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnActionEdit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cha = lv_label_create(ui_BtnActionEdit);
    lv_obj_set_width(ui_Cha, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cha, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Cha, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cha, "Effect Parameters");
    lv_obj_set_style_text_color(ui_Cha, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Cha, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton5 = lv_imgbtn_create(ui_Container2);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_discover_tune_45dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 45);
    lv_obj_set_height(ui_ImgButton5, 45);
    lv_obj_set_x(ui_ImgButton5, 24);
    lv_obj_set_y(ui_ImgButton5, -2);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_DifferentEffects);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 136);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 87);
    lv_obj_set_y(ui_Container1, 100);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x00D1FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BtnActionReplace = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnActionReplace, 95);
    lv_obj_set_height(ui_BtnActionReplace, 44);
    lv_obj_set_x(ui_BtnActionReplace, 182);
    lv_obj_set_y(ui_BtnActionReplace, 99);
    lv_obj_set_align(ui_BtnActionReplace, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnActionReplace, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnActionReplace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnActionReplace, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnActionReplace, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnActionReplace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnActionReplace, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnActionReplace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cha1 = lv_label_create(ui_BtnActionReplace);
    lv_obj_set_width(ui_Cha1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cha1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Cha1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cha1, "Effect Chain");
    lv_obj_set_style_text_color(ui_Cha1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Cha1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Container1);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_add_link_45dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 45);
    lv_obj_set_height(ui_ImgButton2, 45);
    lv_obj_set_x(ui_ImgButton2, 24);
    lv_obj_set_y(ui_ImgButton2, -2);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_BtnEffectsBack, ui_event_BtnEffectsBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDelayIcon, ui_event_BtnDelayIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnReverbIcon, ui_event_BtnReverbIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCompressorIcon, ui_event_BtnCompressorIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDistortionIcon, ui_event_BtnDistortionIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnChorusIcon, ui_event_BtnChorusIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCabIcon, ui_event_BtnCabIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnAmpIcon, ui_event_BtnAmpIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnEQIcon, ui_event_BtnEQIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnActionEdit, ui_event_BtnActionEdit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnActionReplace, ui_event_BtnActionReplace, LV_EVENT_ALL, NULL);

}

void ui_DifferentEffects_screen_destroy(void)
{
    if(ui_DifferentEffects) lv_obj_del(ui_DifferentEffects);

    // NULL screen variables
    ui_DifferentEffects = NULL;
    ui_PanelEffects = NULL;
    ui_LabelEffectsTitle = NULL;
    ui_BtnEffectsBack = NULL;
    ui_BlockDelay = NULL;
    ui_BtnDelayIcon = NULL;
    ui_LabelDelay = NULL;
    ui_LabelEffect02 = NULL;
    ui_SwitchDelayToggle = NULL;
    ui_BlockReverb = NULL;
    ui_BtnReverbIcon = NULL;
    ui_LabelEffect01 = NULL;
    ui_LabelReverb = NULL;
    ui_SwitchReverbToggle = NULL;
    ui_BlockCompressor = NULL;
    ui_BtnCompressorIcon = NULL;
    ui_LabelComp = NULL;
    ui_LabelEffect04 = NULL;
    ui_SwitchCompressorToggle = NULL;
    ui_BlockDistortion = NULL;
    ui_BtnDistortionIcon = NULL;
    ui_LabelDistortion = NULL;
    ui_SwitchDistortionToggle = NULL;
    ui_LabelEffect03 = NULL;
    ui_BlockChorus = NULL;
    ui_BtnChorusIcon = NULL;
    ui_LabelChorus = NULL;
    ui_LabelEffect05 = NULL;
    ui_SwitchChorusToggle = NULL;
    ui_BlockCab = NULL;
    ui_BtnCabIcon = NULL;
    ui_SwitchCabToggle = NULL;
    ui_LabelCABIR = NULL;
    ui_LabelEffect06 = NULL;
    ui_BlockAmp = NULL;
    ui_BtnAmpIcon = NULL;
    ui_SwitchAmpToggle = NULL;
    ui_LabelAmp = NULL;
    ui_LabelEffect07 = NULL;
    ui_BlockEQ = NULL;
    ui_BtnEQIcon = NULL;
    ui_LabelEQ = NULL;
    ui_LabelEffect08 = NULL;
    ui_SwitchEQToggle = NULL;
    ui_PanelEffectSelector = NULL;
    ui_Container2 = NULL;
    ui_BtnActionEdit = NULL;
    ui_Cha = NULL;
    ui_ImgButton5 = NULL;
    ui_Container1 = NULL;
    ui_BtnActionReplace = NULL;
    ui_Cha1 = NULL;
    ui_ImgButton2 = NULL;

}
