// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DIFFERENTEFFECTS_H
#define UI_DIFFERENTEFFECTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DifferentEffects
extern void ui_DifferentEffects_screen_init(void);
extern void ui_DifferentEffects_screen_destroy(void);
extern lv_obj_t * ui_DifferentEffects;
extern lv_obj_t * ui_PanelEffects;
extern lv_obj_t * ui_LabelEffectsTitle;
extern void ui_event_BtnEffectsBack(lv_event_t * e);
extern lv_obj_t * ui_BtnEffectsBack;
extern lv_obj_t * ui_BlockDelay;
extern void ui_event_BtnDelayIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnDelayIcon;
extern lv_obj_t * ui_LabelDelay;
extern lv_obj_t * ui_LabelEffect02;
extern lv_obj_t * ui_SwitchDelayToggle;
extern lv_obj_t * ui_BlockReverb;
extern void ui_event_BtnReverbIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnReverbIcon;
extern lv_obj_t * ui_LabelEffect01;
extern lv_obj_t * ui_LabelReverb;
extern lv_obj_t * ui_SwitchReverbToggle;
extern lv_obj_t * ui_BlockCompressor;
extern void ui_event_BtnCompressorIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnCompressorIcon;
extern lv_obj_t * ui_LabelComp;
extern lv_obj_t * ui_LabelEffect04;
extern lv_obj_t * ui_SwitchCompressorToggle;
extern lv_obj_t * ui_BlockDistortion;
extern void ui_event_BtnDistortionIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnDistortionIcon;
extern lv_obj_t * ui_LabelDistortion;
extern lv_obj_t * ui_SwitchDistortionToggle;
extern lv_obj_t * ui_LabelEffect03;
extern lv_obj_t * ui_BlockChorus;
extern void ui_event_BtnChorusIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnChorusIcon;
extern lv_obj_t * ui_LabelChorus;
extern lv_obj_t * ui_LabelEffect05;
extern lv_obj_t * ui_SwitchChorusToggle;
extern lv_obj_t * ui_BlockCab;
extern void ui_event_BtnCabIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnCabIcon;
extern lv_obj_t * ui_SwitchCabToggle;
extern lv_obj_t * ui_LabelCABIR;
extern lv_obj_t * ui_LabelEffect06;
extern lv_obj_t * ui_BlockAmp;
extern void ui_event_BtnAmpIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnAmpIcon;
extern lv_obj_t * ui_SwitchAmpToggle;
extern lv_obj_t * ui_LabelAmp;
extern lv_obj_t * ui_LabelEffect07;
extern lv_obj_t * ui_BlockEQ;
extern void ui_event_BtnEQIcon(lv_event_t * e);
extern lv_obj_t * ui_BtnEQIcon;
extern lv_obj_t * ui_LabelEQ;
extern lv_obj_t * ui_LabelEffect08;
extern lv_obj_t * ui_SwitchEQToggle;
extern lv_obj_t * ui_PanelEffectSelector;
extern lv_obj_t * ui_Container2;
extern void ui_event_BtnActionEdit(lv_event_t * e);
extern lv_obj_t * ui_BtnActionEdit;
extern lv_obj_t * ui_Cha;
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Container1;
extern void ui_event_BtnActionReplace(lv_event_t * e);
extern lv_obj_t * ui_BtnActionReplace;
extern lv_obj_t * ui_Cha1;
extern lv_obj_t * ui_ImgButton2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

