// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_EFFECTCHAIN_H
#define UI_EFFECTCHAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Effectchain
extern void ui_Effectchain_screen_init(void);
extern void ui_Effectchain_screen_destroy(void);
extern lv_obj_t * ui_Effectchain;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Effect8;
extern void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Roller3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

