// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void slider_value_changed(lv_event_t * e);
void ui_event_BtnPreset1(lv_event_t * e);
void ui_event_BtnPreset2(lv_event_t * e);
void ui_event_BtnPreset3(lv_event_t * e);
void SelectActiveSlot(lv_event_t * e);
void OnBtnEditParamsClicked(lv_event_t * e);
void OnBtnReplaceClicked(lv_event_t * e);
void UpdateSlotEffect(lv_event_t * e);
void ui_event_CheckboxMono(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif