// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Effectchain = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Effect8 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_Roller3 = NULL;
// event funtions
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_Effectchain_screen_init(void)
{
    ui_Effectchain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Effectchain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Effectchain);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_height(ui_Panel6, lv_pct(20));
    lv_obj_set_x(ui_Panel6, lv_pct(0));
    lv_obj_set_y(ui_Panel6, lv_pct(-40));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x009DF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect8 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Effect8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect8, "Effect Chain");

    ui_ImgButton6 = lv_imgbtn_create(ui_Effectchain);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_ImgButton6, 20);
    lv_obj_set_height(ui_ImgButton6, 32);
    lv_obj_set_x(ui_ImgButton6, -144);
    lv_obj_set_y(ui_ImgButton6, -97);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Roller3 = lv_roller_create(ui_Effectchain);
    lv_roller_set_options(ui_Roller3, "Tuner\nWah\nOverdrive\nDistortion\nEQ\nChorus\nDelay\nReverb",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller3, 182);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, 0);
    lv_obj_set_y(ui_Roller3, 25);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}

void ui_Effectchain_screen_destroy(void)
{
    if(ui_Effectchain) lv_obj_del(ui_Effectchain);

    // NULL screen variables
    ui_Effectchain = NULL;
    ui_Panel6 = NULL;
    ui_Effect8 = NULL;
    ui_ImgButton6 = NULL;
    ui_Roller3 = NULL;

}
