// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_InputGain;
lv_obj_t * ui_InputGain = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Effect2 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_Arc10 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_InputGain_screen_init(void)
{
    ui_InputGain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InputGain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InputGain, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_InputGain);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(20));
    lv_obj_set_x(ui_Panel2, lv_pct(0));
    lv_obj_set_y(ui_Panel2, lv_pct(-40));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x009DF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Effect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect2, "Input Gain");

    ui_ImgButton3 = lv_imgbtn_create(ui_InputGain);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_ImgButton3, 20);
    lv_obj_set_height(ui_ImgButton3, 32);
    lv_obj_set_x(ui_ImgButton3, -144);
    lv_obj_set_y(ui_ImgButton3, -97);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Arc10 = lv_arc_create(ui_InputGain);
    lv_obj_set_width(ui_Arc10, 173);
    lv_obj_set_height(ui_Arc10, 171);
    lv_obj_set_x(ui_Arc10, 0);
    lv_obj_set_y(ui_Arc10, 35);
    lv_obj_set_align(ui_Arc10, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc10, 50);

    ui_Label8 = lv_label_create(ui_InputGain);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 5);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Gain");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_InputGain);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 35);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "0 dB");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    uic_InputGain = ui_InputGain;

}

void ui_InputGain_screen_destroy(void)
{
    if(ui_InputGain) lv_obj_del(ui_InputGain);

    // NULL screen variables
    uic_InputGain = NULL;
    ui_InputGain = NULL;
    ui_Panel2 = NULL;
    ui_Effect2 = NULL;
    ui_ImgButton3 = NULL;
    ui_Arc10 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;

}
