// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_INPUTGAIN_H
#define UI_INPUTGAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InputGain
extern void ui_InputGain_screen_init(void);
extern void ui_InputGain_screen_destroy(void);
extern lv_obj_t * ui_InputGain;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Effect2;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Arc10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_InputGain;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

