// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_InputGain;
lv_obj_t * ui_LabelInputTitle = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Effect2 = NULL;
lv_obj_t * ui_BtnInputBack = NULL;
lv_obj_t * ui_ArcInputGain = NULL;
lv_obj_t * ui_LabelInputText = NULL;
lv_obj_t * ui_LabelInputValue = NULL;
lv_obj_t * ui_LabelInputUnit = NULL;
// event funtions
void ui_event_BtnInputBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_TitleMenuHeader, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_TitleMenuHeader_screen_init);
    }
}

void ui_event_ArcInputGain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_value_changed(e);
    }
}

// build funtions

void ui_LabelInputTitle_screen_init(void)
{
    ui_LabelInputTitle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LabelInputTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LabelInputTitle, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelInputTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_LabelInputTitle);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(20));
    lv_obj_set_x(ui_Panel2, lv_pct(0));
    lv_obj_set_y(ui_Panel2, lv_pct(-40));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Effect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect2, "Input Gain");

    ui_BtnInputBack = lv_imgbtn_create(ui_LabelInputTitle);
    lv_imgbtn_set_src(ui_BtnInputBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnInputBack, 30);
    lv_obj_set_height(ui_BtnInputBack, 40);
    lv_obj_set_x(ui_BtnInputBack, -139);
    lv_obj_set_y(ui_BtnInputBack, -93);
    lv_obj_set_align(ui_BtnInputBack, LV_ALIGN_CENTER);

    ui_ArcInputGain = lv_arc_create(ui_LabelInputTitle);
    lv_obj_set_width(ui_ArcInputGain, 173);
    lv_obj_set_height(ui_ArcInputGain, 171);
    lv_obj_set_x(ui_ArcInputGain, 0);
    lv_obj_set_y(ui_ArcInputGain, 35);
    lv_obj_set_align(ui_ArcInputGain, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcInputGain, -40, 0);
    lv_arc_set_value(ui_ArcInputGain, -40);

    ui_LabelInputText = lv_label_create(ui_LabelInputTitle);
    lv_obj_set_width(ui_LabelInputText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInputText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInputText, 0);
    lv_obj_set_y(ui_LabelInputText, 5);
    lv_obj_set_align(ui_LabelInputText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInputText, "Gain");
    lv_obj_set_style_text_color(ui_LabelInputText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInputText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInputValue = lv_label_create(ui_LabelInputTitle);
    lv_obj_set_width(ui_LabelInputValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInputValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInputValue, 0);
    lv_obj_set_y(ui_LabelInputValue, 35);
    lv_obj_set_align(ui_LabelInputValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInputValue, "0");
    lv_obj_set_style_text_color(ui_LabelInputValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInputValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInputUnit = lv_label_create(ui_LabelInputTitle);
    lv_obj_set_width(ui_LabelInputUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInputUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInputUnit, 25);
    lv_obj_set_y(ui_LabelInputUnit, 35);
    lv_obj_set_align(ui_LabelInputUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInputUnit, "dB");
    lv_obj_set_style_text_color(ui_LabelInputUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInputUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnInputBack, ui_event_BtnInputBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcInputGain, ui_event_ArcInputGain, LV_EVENT_ALL, NULL);
    uic_InputGain = ui_LabelInputTitle;

}

void ui_LabelInputTitle_screen_destroy(void)
{
    if(ui_LabelInputTitle) lv_obj_del(ui_LabelInputTitle);

    // NULL screen variables
    uic_InputGain = NULL;
    ui_LabelInputTitle = NULL;
    ui_Panel2 = NULL;
    ui_Effect2 = NULL;
    ui_BtnInputBack = NULL;
    ui_ArcInputGain = NULL;
    ui_LabelInputText = NULL;
    ui_LabelInputValue = NULL;
    ui_LabelInputUnit = NULL;

}
