// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LABELINPUTTITLE_H
#define UI_LABELINPUTTITLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LabelInputTitle
extern void ui_LabelInputTitle_screen_init(void);
extern void ui_LabelInputTitle_screen_destroy(void);
extern lv_obj_t * ui_LabelInputTitle;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Effect2;
extern void ui_event_BtnInputBack(lv_event_t * e);
extern lv_obj_t * ui_BtnInputBack;
extern void ui_event_ArcInputGain(lv_event_t * e);
extern lv_obj_t * ui_ArcInputGain;
extern lv_obj_t * ui_LabelInputText;
extern lv_obj_t * ui_LabelInputValue;
extern lv_obj_t * ui_LabelInputUnit;
// CUSTOM VARIABLES
extern lv_obj_t * uic_InputGain;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

