// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_OutputLevel;
lv_obj_t * ui_OutputBack = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Effect3 = NULL;
lv_obj_t * ui_BtnOutputsBack = NULL;
lv_obj_t * ui_SliderOutputLevel = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_CheckboxOutputMute = NULL;
lv_obj_t * ui_ValueOutputLevel = NULL;
// event funtions
void ui_event_BtnOutputsBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_TitleMenuHeader, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_TitleMenuHeader_screen_init);
    }
}

void ui_event_SliderOutputLevel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_value_changed(e);
    }
}

// build funtions

void ui_OutputBack_screen_init(void)
{
    ui_OutputBack = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OutputBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputBack, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_OutputBack);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(20));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(-40));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Effect3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect3, "Output Level");

    ui_BtnOutputsBack = lv_imgbtn_create(ui_OutputBack);
    lv_imgbtn_set_src(ui_BtnOutputsBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnOutputsBack, 32);
    lv_obj_set_height(ui_BtnOutputsBack, 39);
    lv_obj_set_x(ui_BtnOutputsBack, -137);
    lv_obj_set_y(ui_BtnOutputsBack, -94);
    lv_obj_set_align(ui_BtnOutputsBack, LV_ALIGN_CENTER);

    ui_SliderOutputLevel = lv_slider_create(ui_OutputBack);
    lv_slider_set_value(ui_SliderOutputLevel, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderOutputLevel) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderOutputLevel, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderOutputLevel, 265);
    lv_obj_set_height(ui_SliderOutputLevel, 25);
    lv_obj_set_x(ui_SliderOutputLevel, 0);
    lv_obj_set_y(ui_SliderOutputLevel, 20);
    lv_obj_set_align(ui_SliderOutputLevel, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_OutputBack);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -50);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Value");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxOutputMute = lv_checkbox_create(ui_OutputBack);
    lv_checkbox_set_text(ui_CheckboxOutputMute, "Mute");
    lv_obj_set_width(ui_CheckboxOutputMute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxOutputMute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxOutputMute, 0);
    lv_obj_set_y(ui_CheckboxOutputMute, 75);
    lv_obj_set_align(ui_CheckboxOutputMute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxOutputMute, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxOutputMute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxOutputMute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueOutputLevel = lv_label_create(ui_OutputBack);
    lv_obj_set_width(ui_ValueOutputLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueOutputLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueOutputLevel, 1);
    lv_obj_set_y(ui_ValueOutputLevel, -25);
    lv_obj_set_align(ui_ValueOutputLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueOutputLevel, "0");
    lv_obj_set_style_text_color(ui_ValueOutputLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueOutputLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnOutputsBack, ui_event_BtnOutputsBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderOutputLevel, ui_event_SliderOutputLevel, LV_EVENT_ALL, NULL);
    uic_OutputLevel = ui_OutputBack;

}

void ui_OutputBack_screen_destroy(void)
{
    if(ui_OutputBack) lv_obj_del(ui_OutputBack);

    // NULL screen variables
    uic_OutputLevel = NULL;
    ui_OutputBack = NULL;
    ui_Panel4 = NULL;
    ui_Effect3 = NULL;
    ui_BtnOutputsBack = NULL;
    ui_SliderOutputLevel = NULL;
    ui_Label10 = NULL;
    ui_CheckboxOutputMute = NULL;
    ui_ValueOutputLevel = NULL;

}
