// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_OutputLevel;
lv_obj_t * ui_OutputLevel = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Effect3 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Slider14 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Checkbox2 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_OutputLevel_screen_init(void)
{
    ui_OutputLevel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OutputLevel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputLevel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_OutputLevel);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(20));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(-40));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x009DF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Effect3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect3, "Output Level");

    ui_ImgButton4 = lv_imgbtn_create(ui_OutputLevel);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_ImgButton4, 20);
    lv_obj_set_height(ui_ImgButton4, 32);
    lv_obj_set_x(ui_ImgButton4, -144);
    lv_obj_set_y(ui_ImgButton4, -97);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_Slider14 = lv_slider_create(ui_OutputLevel);
    lv_slider_set_value(ui_Slider14, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider14) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider14, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider14, 265);
    lv_obj_set_height(ui_Slider14, 25);
    lv_obj_set_x(ui_Slider14, 0);
    lv_obj_set_y(ui_Slider14, 20);
    lv_obj_set_align(ui_Slider14, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_OutputLevel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -50);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Value");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox2 = lv_checkbox_create(ui_OutputLevel);
    lv_checkbox_set_text(ui_Checkbox2, "Mute");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, 0);
    lv_obj_set_y(ui_Checkbox2, 75);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_OutputLevel);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 1);
    lv_obj_set_y(ui_Label11, -25);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "0");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    uic_OutputLevel = ui_OutputLevel;

}

void ui_OutputLevel_screen_destroy(void)
{
    if(ui_OutputLevel) lv_obj_del(ui_OutputLevel);

    // NULL screen variables
    uic_OutputLevel = NULL;
    ui_OutputLevel = NULL;
    ui_Panel4 = NULL;
    ui_Effect3 = NULL;
    ui_ImgButton4 = NULL;
    ui_Slider14 = NULL;
    ui_Label10 = NULL;
    ui_Checkbox2 = NULL;
    ui_Label11 = NULL;

}
