// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OUTPUTBACK_H
#define UI_OUTPUTBACK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OutputBack
extern void ui_OutputBack_screen_init(void);
extern void ui_OutputBack_screen_destroy(void);
extern lv_obj_t * ui_OutputBack;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Effect3;
extern void ui_event_BtnOutputsBack(lv_event_t * e);
extern lv_obj_t * ui_BtnOutputsBack;
extern void ui_event_SliderOutputLevel(lv_event_t * e);
extern lv_obj_t * ui_SliderOutputLevel;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_CheckboxOutputMute;
extern lv_obj_t * ui_ValueOutputLevel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_OutputLevel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

