// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OUTPUTLEVEL_H
#define UI_OUTPUTLEVEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OutputLevel
extern void ui_OutputLevel_screen_init(void);
extern void ui_OutputLevel_screen_destroy(void);
extern lv_obj_t * ui_OutputLevel;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Effect3;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Slider14;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_OutputLevel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

