// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern void ui_event_CheckboxMono(lv_event_t * e);

lv_obj_t * uic_Effect;
lv_obj_t * uic_ScreenEffects;
lv_obj_t * ui_PanelEditHeader = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_LabelEditTitle = NULL;
lv_obj_t * ui_BtnEditBack = NULL;
lv_obj_t * ui_LabelParam1 = NULL;
lv_obj_t * ui_SliderParam1 = NULL;
lv_obj_t * ui_LabelParam2 = NULL;
lv_obj_t * ui_SliderParam2 = NULL;
lv_obj_t * ui_LabelParam3 = NULL;
lv_obj_t * ui_SliderParam3 = NULL;
lv_obj_t * ui_LabelParam4 = NULL;
lv_obj_t * ui_SliderParam4 = NULL;
lv_obj_t * ui_LabelParam5 = NULL;
lv_obj_t * ui_SliderParam5 = NULL;
lv_obj_t * ui_LabelParam6 = NULL;
lv_obj_t * ui_SliderParam6 = NULL;
lv_obj_t * ui_LabelParam7 = NULL;
lv_obj_t * ui_SliderParam7 = NULL;
lv_obj_t * ui_LabelParam8 = NULL;
lv_obj_t * ui_SliderParam8 = NULL;
lv_obj_t * ui_CheckboxMono = NULL;
lv_obj_t * ui_CheckboxStr1 = NULL;
lv_obj_t * ui_CheckboxStr2 = NULL;
lv_obj_t * ui_CheckboxStr3 = NULL;
lv_obj_t * ui_CheckboxStr4 = NULL;
lv_obj_t * ui_CheckboxStr5 = NULL;
lv_obj_t * ui_CheckboxStr6 = NULL;

// event funtions
void ui_event_BtnEditBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DifferentEffects, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_DifferentEffects_screen_init);
    }
}

// build funtions

void ui_PanelEditHeader_screen_init(void)
{
    ui_PanelEditHeader = lv_obj_create(NULL);
    lv_obj_add_flag(ui_PanelEditHeader, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelEditHeader, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelEditHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(20));
    lv_obj_set_x(ui_Panel3, lv_pct(0));
    lv_obj_set_y(ui_Panel3, lv_pct(-40));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEditTitle = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelEditTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEditTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEditTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEditTitle, "Effect Name");

    ui_BtnEditBack = lv_imgbtn_create(ui_PanelEditHeader);
    lv_imgbtn_set_src(ui_BtnEditBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnEditBack, 30);
    lv_obj_set_height(ui_BtnEditBack, 41);
    lv_obj_set_x(ui_BtnEditBack, -138);
    lv_obj_set_y(ui_BtnEditBack, -92);
    lv_obj_set_align(ui_BtnEditBack, LV_ALIGN_CENTER);

    ui_LabelParam1 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam1, -115);
    lv_obj_set_y(ui_LabelParam1, -50);
    lv_obj_set_align(ui_LabelParam1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam1, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam1 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam1, 200);
    lv_obj_set_height(ui_SliderParam1, 17);
    lv_obj_set_x(ui_SliderParam1, 40);
    lv_obj_set_y(ui_SliderParam1, -50);
    lv_obj_set_align(ui_SliderParam1, LV_ALIGN_CENTER);

    ui_LabelParam2 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam2, -115);
    lv_obj_set_y(ui_LabelParam2, -10);
    lv_obj_set_align(ui_LabelParam2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam2, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam2 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam2, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam2, 200);
    lv_obj_set_height(ui_SliderParam2, 17);
    lv_obj_set_x(ui_SliderParam2, 40);
    lv_obj_set_y(ui_SliderParam2, -10);
    lv_obj_set_align(ui_SliderParam2, LV_ALIGN_CENTER);

    ui_LabelParam3 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam3, -115);
    lv_obj_set_y(ui_LabelParam3, 30);
    lv_obj_set_align(ui_LabelParam3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam3, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam3 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam3, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam3, 200);
    lv_obj_set_height(ui_SliderParam3, 17);
    lv_obj_set_x(ui_SliderParam3, 40);
    lv_obj_set_y(ui_SliderParam3, 30);
    lv_obj_set_align(ui_SliderParam3, LV_ALIGN_CENTER);

    ui_LabelParam4 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam4, -115);
    lv_obj_set_y(ui_LabelParam4, 70);
    lv_obj_set_align(ui_LabelParam4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam4, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam4 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam4, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam4, 200);
    lv_obj_set_height(ui_SliderParam4, 17);
    lv_obj_set_x(ui_SliderParam4, 40);
    lv_obj_set_y(ui_SliderParam4, 70);
    lv_obj_set_align(ui_SliderParam4, LV_ALIGN_CENTER);

    ui_LabelParam5 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam5, -115);
    lv_obj_set_y(ui_LabelParam5, 110);
    lv_obj_set_align(ui_LabelParam5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam5, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam5 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam5, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam5, 200);
    lv_obj_set_height(ui_SliderParam5, 17);
    lv_obj_set_x(ui_SliderParam5, 41);
    lv_obj_set_y(ui_SliderParam5, 110);
    lv_obj_set_align(ui_SliderParam5, LV_ALIGN_CENTER);

    ui_LabelParam6 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam6, -115);
    lv_obj_set_y(ui_LabelParam6, 150);
    lv_obj_set_align(ui_LabelParam6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam6, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam6 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam6, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam6, 200);
    lv_obj_set_height(ui_SliderParam6, 17);
    lv_obj_set_x(ui_SliderParam6, 40);
    lv_obj_set_y(ui_SliderParam6, 150);
    lv_obj_set_align(ui_SliderParam6, LV_ALIGN_CENTER);

    ui_LabelParam7 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam7, -115);
    lv_obj_set_y(ui_LabelParam7, 190);
    lv_obj_set_align(ui_LabelParam7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam7, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam7 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam7, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam7, 200);
    lv_obj_set_height(ui_SliderParam7, 17);
    lv_obj_set_x(ui_SliderParam7, 41);
    lv_obj_set_y(ui_SliderParam7, 190);
    lv_obj_set_align(ui_SliderParam7, LV_ALIGN_CENTER);

    ui_LabelParam8 = lv_label_create(ui_PanelEditHeader);
    lv_obj_set_width(ui_LabelParam8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelParam8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelParam8, -115);
    lv_obj_set_y(ui_LabelParam8, 230);
    lv_obj_set_align(ui_LabelParam8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelParam8, "Parameter");
    lv_obj_set_style_text_color(ui_LabelParam8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelParam8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderParam8 = lv_slider_create(ui_PanelEditHeader);
    lv_slider_set_value(ui_SliderParam8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderParam8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderParam8, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderParam8, 200);
    lv_obj_set_height(ui_SliderParam8, 17);
    lv_obj_set_x(ui_SliderParam8, 41);
    lv_obj_set_y(ui_SliderParam8, 230);
    lv_obj_set_align(ui_SliderParam8, LV_ALIGN_CENTER);

    ui_CheckboxMono = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxMono, "Mono");
    lv_obj_set_width(ui_CheckboxMono, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxMono, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxMono, -115);
    lv_obj_set_y(ui_CheckboxMono, 270);
    lv_obj_set_align(ui_CheckboxMono, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxMono, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxMono, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxMono, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr1 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr1, "String 1");
    lv_obj_set_width(ui_CheckboxStr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr1, -108);
    lv_obj_set_y(ui_CheckboxStr1, 300);
    lv_obj_set_align(ui_CheckboxStr1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr2 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr2, "String 2");
    lv_obj_set_width(ui_CheckboxStr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr2, 19);
    lv_obj_set_y(ui_CheckboxStr2, 300);
    lv_obj_set_align(ui_CheckboxStr2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr3 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr3, "String 3");
    lv_obj_set_width(ui_CheckboxStr3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr3, -107);
    lv_obj_set_y(ui_CheckboxStr3, 330);
    lv_obj_set_align(ui_CheckboxStr3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr4 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr4, "String 4");
    lv_obj_set_width(ui_CheckboxStr4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr4, 20);
    lv_obj_set_y(ui_CheckboxStr4, 330);
    lv_obj_set_align(ui_CheckboxStr4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr5 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr5, "String 5");
    lv_obj_set_width(ui_CheckboxStr5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr5, -107);
    lv_obj_set_y(ui_CheckboxStr5, 360);
    lv_obj_set_align(ui_CheckboxStr5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStr6 = lv_checkbox_create(ui_PanelEditHeader);
    lv_checkbox_set_text(ui_CheckboxStr6, "String 6");
    lv_obj_set_width(ui_CheckboxStr6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStr6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStr6, 20);
    lv_obj_set_y(ui_CheckboxStr6, 360);
    lv_obj_set_align(ui_CheckboxStr6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStr6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxStr6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxStr6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnEditBack, ui_event_BtnEditBack, LV_EVENT_ALL, NULL);

    // Event connections for Sliders
    lv_obj_add_event_cb(ui_SliderParam1, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam2, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam3, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam4, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam5, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam6, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam7, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_SliderParam8, slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Event connection for CheckboxMono
    lv_obj_add_event_cb(ui_CheckboxMono, ui_event_CheckboxMono, LV_EVENT_VALUE_CHANGED, NULL);

    uic_ScreenEffects = ui_PanelEditHeader;
    uic_Effect = ui_LabelEditTitle;

}

void ui_PanelEditHeader_screen_destroy(void)
{
    if(ui_PanelEditHeader) lv_obj_del(ui_PanelEditHeader);

    // NULL screen variables
    uic_ScreenEffects = NULL;
    ui_PanelEditHeader = NULL;
    ui_Panel3 = NULL;
    uic_Effect = NULL;
    ui_LabelEditTitle = NULL;
    ui_BtnEditBack = NULL;
    ui_LabelParam1 = NULL;
    ui_SliderParam1 = NULL;
    ui_LabelParam2 = NULL;
    ui_SliderParam2 = NULL;
    ui_LabelParam3 = NULL;
    ui_SliderParam3 = NULL;
    ui_LabelParam4 = NULL;
    ui_SliderParam4 = NULL;
    ui_LabelParam5 = NULL;
    ui_SliderParam5 = NULL;
    ui_LabelParam6 = NULL;
    ui_SliderParam6 = NULL;
    ui_LabelParam7 = NULL;
    ui_SliderParam7 = NULL;
    ui_LabelParam8 = NULL;
    ui_SliderParam8 = NULL;
    ui_CheckboxMono = NULL;
    ui_CheckboxStr1 = NULL;
    ui_CheckboxStr2 = NULL;
    ui_CheckboxStr3 = NULL;
    ui_CheckboxStr4 = NULL;
    ui_CheckboxStr5 = NULL;
    ui_CheckboxStr6 = NULL;

}