// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PANELEDITHEADER_H
#define UI_PANELEDITHEADER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PanelEditHeader
extern void ui_PanelEditHeader_screen_init(void);
extern void ui_PanelEditHeader_screen_destroy(void);
extern lv_obj_t * ui_PanelEditHeader;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_LabelEditTitle;
extern void ui_event_BtnEditBack(lv_event_t * e);
extern lv_obj_t * ui_BtnEditBack;
extern lv_obj_t * ui_LabelParam1;
extern lv_obj_t * ui_SliderParam1;
extern lv_obj_t * ui_LabelParam2;
extern lv_obj_t * ui_SliderParam2;
extern lv_obj_t * ui_LabelParam3;
extern lv_obj_t * ui_SliderParam3;
extern lv_obj_t * ui_LabelParam4;
extern lv_obj_t * ui_SliderParam4;
extern lv_obj_t * ui_LabelParam5;
extern lv_obj_t * ui_SliderParam5;
extern lv_obj_t * ui_LabelParam6;
extern lv_obj_t * ui_SliderParam6;
extern lv_obj_t * ui_LabelParam7;
extern lv_obj_t * ui_SliderParam7;
extern lv_obj_t * ui_LabelParam8;
extern lv_obj_t * ui_SliderParam8;
extern lv_obj_t * ui_CheckboxMono;
extern lv_obj_t * ui_CheckboxStr1;
extern lv_obj_t * ui_CheckboxStr2;
extern lv_obj_t * ui_CheckboxStr3;
extern lv_obj_t * ui_CheckboxStr4;
extern lv_obj_t * ui_CheckboxStr5;
extern lv_obj_t * ui_CheckboxStr6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenEffects;
extern lv_obj_t * uic_Effect;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif