// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENEFFECTS_H
#define UI_SCREENEFFECTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenEffects
extern void ui_ScreenEffects_screen_init(void);
extern void ui_ScreenEffects_screen_destroy(void);
extern lv_obj_t * ui_ScreenEffects;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Effect;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Delay;
extern lv_obj_t * ui_Distortion;
extern lv_obj_t * ui_Distortion1;
extern lv_obj_t * ui_Slider10;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Distortion2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Slider6;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Delay1;
extern lv_obj_t * ui_Delay2;
extern lv_obj_t * ui_Slider8;
extern lv_obj_t * ui_Slider7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenEffects;
extern lv_obj_t * uic_Effect;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

