// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENEFFECTSELECTOR_H
#define UI_SCREENEFFECTSELECTOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenEffectSelector
extern void ui_ScreenEffectSelector_screen_init(void);
extern void ui_ScreenEffectSelector_screen_destroy(void);
extern lv_obj_t * ui_ScreenEffectSelector;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelSelectorTitle;
extern void ui_event_BtnEditBack1(lv_event_t * e);
extern lv_obj_t * ui_BtnEditBack1;
extern lv_obj_t * ui_RollerEffectSelect;
extern void ui_event_BtnSelectCancel(lv_event_t * e);
extern lv_obj_t * ui_BtnSelectCancel;
extern void ui_event_BtnSelectConfirm(lv_event_t * e);
extern lv_obj_t * ui_BtnSelectConfirm;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

