// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_System;
lv_obj_t * ui_System = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Effect4 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Effect5 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Effect1 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Effect6 = NULL;
// event funtions
void ui_event_System(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Effectchain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Effectchain_screen_init);
    }
}

void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Effectchain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Effectchain_screen_init);
    }
}

// build funtions

void ui_System_screen_init(void)
{
    ui_System = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_System, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_System, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_System);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, lv_pct(20));
    lv_obj_set_x(ui_Panel5, lv_pct(0));
    lv_obj_set_y(ui_Panel5, lv_pct(-40));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x009DF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect4 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Effect4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect4, "Output Level");

    ui_ImgButton5 = lv_imgbtn_create(ui_System);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_ImgButton5, 20);
    lv_obj_set_height(ui_ImgButton5, 32);
    lv_obj_set_x(ui_ImgButton5, -144);
    lv_obj_set_y(ui_ImgButton5, -97);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_Button14 = lv_btn_create(ui_System);
    lv_obj_set_width(ui_Button14, 320);
    lv_obj_set_height(ui_Button14, 50);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, -40);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Effect5 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Effect5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect5, "Effect Chain");

    ui_Button4 = lv_btn_create(ui_System);
    lv_obj_set_width(ui_Button4, 320);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 20);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Effect1 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Effect1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect1, "Calibrate");

    ui_Button5 = lv_btn_create(ui_System);
    lv_obj_set_width(ui_Button5, 320);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 80);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Effect6 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Effect6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect6, "Settings");

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System, ui_event_System, LV_EVENT_ALL, NULL);
    uic_System = ui_System;

}

void ui_System_screen_destroy(void)
{
    if(ui_System) lv_obj_del(ui_System);

    // NULL screen variables
    uic_System = NULL;
    ui_System = NULL;
    ui_Panel5 = NULL;
    ui_Effect4 = NULL;
    ui_ImgButton5 = NULL;
    ui_Button14 = NULL;
    ui_Effect5 = NULL;
    ui_Button4 = NULL;
    ui_Effect1 = NULL;
    ui_Button5 = NULL;
    ui_Effect6 = NULL;

}
