// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ScreenEffectSelector = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_LabelSelectorTitle = NULL;
lv_obj_t * ui_BtnEditBack1 = NULL;
lv_obj_t * ui_RollerEffectSelect = NULL;
lv_obj_t * ui_BtnSelectCancel = NULL;
lv_obj_t * ui_BtnSelectConfirm = NULL;
// event funtions
void ui_event_BtnEditBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DifferentEffects, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_DifferentEffects_screen_init);
    }
}

void ui_event_BtnSelectCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DifferentEffects, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DifferentEffects_screen_init);
    }
}

void ui_event_BtnSelectConfirm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UpdateSlotEffect(e);
    }
}

// build funtions

void ui_ScreenEffectSelector_screen_init(void)
{
    ui_ScreenEffectSelector = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenEffectSelector, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenEffectSelector, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenEffectSelector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ScreenEffectSelector);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(20));
    lv_obj_set_x(ui_Panel1, lv_pct(0));
    lv_obj_set_y(ui_Panel1, lv_pct(-40));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSelectorTitle = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelSelectorTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSelectorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSelectorTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSelectorTitle, "Change Effect");

    ui_BtnEditBack1 = lv_imgbtn_create(ui_ScreenEffectSelector);
    lv_imgbtn_set_src(ui_BtnEditBack1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnEditBack1, 30);
    lv_obj_set_height(ui_BtnEditBack1, 41);
    lv_obj_set_x(ui_BtnEditBack1, -138);
    lv_obj_set_y(ui_BtnEditBack1, -92);
    lv_obj_set_align(ui_BtnEditBack1, LV_ALIGN_CENTER);

    ui_RollerEffectSelect = lv_roller_create(ui_ScreenEffectSelector);
    // Modified: Removed "Chorus" from options
    lv_roller_set_options(ui_RollerEffectSelect, "Reverb\nDelay\nDistortion\nComp\nAmplifier\nEQ\n\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerEffectSelect, 265);
    lv_obj_set_width(ui_RollerEffectSelect, lv_pct(50));
    lv_obj_set_x(ui_RollerEffectSelect, -75);
    lv_obj_set_y(ui_RollerEffectSelect, 65);
    lv_obj_set_align(ui_RollerEffectSelect, LV_ALIGN_CENTER);

    ui_BtnSelectCancel = lv_imgbtn_create(ui_ScreenEffectSelector);
    lv_imgbtn_set_src(ui_BtnSelectCancel, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_cancel_80dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnSelectCancel, 80);
    lv_obj_set_height(ui_BtnSelectCancel, 80);
    lv_obj_set_x(ui_BtnSelectCancel, 80);
    lv_obj_set_y(ui_BtnSelectCancel, -25);
    lv_obj_set_align(ui_BtnSelectCancel, LV_ALIGN_CENTER);

    ui_BtnSelectConfirm = lv_imgbtn_create(ui_ScreenEffectSelector);
    lv_imgbtn_set_src(ui_BtnSelectConfirm, LV_IMGBTN_STATE_RELEASED, NULL,
                      &ui_img_check_circle_80dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_BtnSelectConfirm, 80);
    lv_obj_set_height(ui_BtnSelectConfirm, 80);
    lv_obj_set_x(ui_BtnSelectConfirm, 80);
    lv_obj_set_y(ui_BtnSelectConfirm, 60);
    lv_obj_set_align(ui_BtnSelectConfirm, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_BtnEditBack1, ui_event_BtnEditBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSelectCancel, ui_event_BtnSelectCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSelectConfirm, ui_event_BtnSelectConfirm, LV_EVENT_ALL, NULL);

}

void ui_ScreenEffectSelector_screen_destroy(void)
{
    if(ui_ScreenEffectSelector) lv_obj_del(ui_ScreenEffectSelector);

    // NULL screen variables
    ui_ScreenEffectSelector = NULL;
    ui_Panel1 = NULL;
    ui_LabelSelectorTitle = NULL;
    ui_BtnEditBack1 = NULL;
    ui_RollerEffectSelect = NULL;
    ui_BtnSelectCancel = NULL;
    ui_BtnSelectConfirm = NULL;

}