// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPRESETSMENU_H
#define UI_SCREENPRESETSMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPresetsMenu
extern void ui_ScreenPresetsMenu_screen_init(void);
extern void ui_ScreenPresetsMenu_screen_destroy(void);
extern lv_obj_t * ui_ScreenPresetsMenu;
extern lv_obj_t * ui_PanelPresetsHeade;
extern lv_obj_t * ui_LabelPresetsTitle;
extern void ui_event_BtnPresetsBack(lv_event_t * e);
extern lv_obj_t * ui_BtnPresetsBack;
extern void ui_event_uiBtnPreset1(lv_event_t * e);
extern lv_obj_t * ui_uiBtnPreset1;
extern lv_obj_t * ui_LabelPreset1;
extern void ui_event_uiBtnPreset2(lv_event_t * e);
extern lv_obj_t * ui_uiBtnPreset2;
extern lv_obj_t * ui_LabelPreset2;
extern void ui_event_uiBtnPreset3(lv_event_t * e);
extern lv_obj_t * ui_uiBtnPreset3;
extern lv_obj_t * ui_LabelPreset3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Presetsmenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

