// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Effect;
lv_obj_t * uic_ScreenEffects;
lv_obj_t * ui_ScreenEffects = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Effect = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Delay = NULL;
lv_obj_t * ui_Distortion = NULL;
lv_obj_t * ui_Distortion1 = NULL;
lv_obj_t * ui_Slider10 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Distortion2 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Slider4 = NULL;
lv_obj_t * ui_Slider5 = NULL;
lv_obj_t * ui_Slider6 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Delay1 = NULL;
lv_obj_t * ui_Delay2 = NULL;
lv_obj_t * ui_Slider8 = NULL;
lv_obj_t * ui_Slider7 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_ScreenEffects_screen_init(void)
{
    ui_ScreenEffects = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenEffects, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenEffects, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenEffects, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(20));
    lv_obj_set_x(ui_Panel3, lv_pct(0));
    lv_obj_set_y(ui_Panel3, lv_pct(-40));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x009DF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Effect = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Effect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Effect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Effect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Effect, "Effects");

    ui_Label6 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label6, -50);
    lv_obj_set_x(ui_Label6, lv_pct(-40));
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Reverb");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Delay = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Delay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Delay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Delay, -112);
    lv_obj_set_y(ui_Delay, 160);
    lv_obj_set_align(ui_Delay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Delay, "C Wet/Dry");
    lv_obj_set_style_text_color(ui_Delay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Delay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Distortion = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Distortion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distortion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distortion, -117);
    lv_obj_set_y(ui_Distortion, 125);
    lv_obj_set_align(ui_Distortion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distortion, "LFO rate");
    lv_obj_set_style_text_color(ui_Distortion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distortion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Distortion1 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Distortion1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distortion1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distortion1, -123);
    lv_obj_set_y(ui_Distortion1, 55);
    lv_obj_set_align(ui_Distortion1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distortion1, "Chorus");
    lv_obj_set_style_text_color(ui_Distortion1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distortion1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider10 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider10, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider10) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider10, 188);
    lv_obj_set_height(ui_Slider10, 10);
    lv_obj_set_x(ui_Slider10, 47);
    lv_obj_set_y(ui_Slider10, -50);
    lv_obj_set_align(ui_Slider10, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label1, -15);
    lv_obj_set_x(ui_Label1, lv_pct(-34));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Reverb time");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_x(ui_Label7, lv_pct(-35));
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "R Wet/Dry");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Distortion2 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Distortion2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distortion2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distortion2, -125);
    lv_obj_set_y(ui_Distortion2, 90);
    lv_obj_set_align(ui_Distortion2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distortion2, "Voices");
    lv_obj_set_style_text_color(ui_Distortion2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distortion2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 188);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 47);
    lv_obj_set_y(ui_Slider1, -15);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Slider2 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 188);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 47);
    lv_obj_set_y(ui_Slider2, 20);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    ui_Slider3 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 188);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, 47);
    lv_obj_set_y(ui_Slider3, 55);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);

    ui_Slider4 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 188);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, 47);
    lv_obj_set_y(ui_Slider4, 90);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);

    ui_Slider5 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 188);
    lv_obj_set_height(ui_Slider5, 10);
    lv_obj_set_x(ui_Slider5, 47);
    lv_obj_set_y(ui_Slider5, 125);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);

    ui_Slider6 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 188);
    lv_obj_set_height(ui_Slider6, 10);
    lv_obj_set_x(ui_Slider6, 47);
    lv_obj_set_y(ui_Slider6, 160);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);

    ui_ImgButton2 = lv_imgbtn_create(ui_ScreenEffects);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_ImgButton2, 20);
    lv_obj_set_height(ui_ImgButton2, 32);
    lv_obj_set_x(ui_ImgButton2, -144);
    lv_obj_set_y(ui_ImgButton2, -97);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Delay1 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Delay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Delay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Delay1, -128);
    lv_obj_set_y(ui_Delay1, 195);
    lv_obj_set_align(ui_Delay1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Delay1, "Delay");
    lv_obj_add_flag(ui_Delay1, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_text_color(ui_Delay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Delay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Delay2 = lv_label_create(ui_ScreenEffects);
    lv_obj_set_width(ui_Delay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Delay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Delay2, -112);
    lv_obj_set_y(ui_Delay2, 230);
    lv_obj_set_align(ui_Delay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Delay2, "Distortion");
    lv_obj_add_flag(ui_Delay2, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_text_color(ui_Delay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Delay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider8 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider8, 188);
    lv_obj_set_height(ui_Slider8, 10);
    lv_obj_set_x(ui_Slider8, 47);
    lv_obj_set_y(ui_Slider8, 195);
    lv_obj_set_align(ui_Slider8, LV_ALIGN_CENTER);

    ui_Slider7 = lv_slider_create(ui_ScreenEffects);
    lv_slider_set_value(ui_Slider7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 188);
    lv_obj_set_height(ui_Slider7, 10);
    lv_obj_set_x(ui_Slider7, 47);
    lv_obj_set_y(ui_Slider7, 230);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    uic_ScreenEffects = ui_ScreenEffects;
    uic_Effect = ui_Effect;

}

void ui_ScreenEffects_screen_destroy(void)
{
    if(ui_ScreenEffects) lv_obj_del(ui_ScreenEffects);

    // NULL screen variables
    uic_ScreenEffects = NULL;
    ui_ScreenEffects = NULL;
    ui_Panel3 = NULL;
    uic_Effect = NULL;
    ui_Effect = NULL;
    ui_Label6 = NULL;
    ui_Delay = NULL;
    ui_Distortion = NULL;
    ui_Distortion1 = NULL;
    ui_Slider10 = NULL;
    ui_Label1 = NULL;
    ui_Label7 = NULL;
    ui_Distortion2 = NULL;
    ui_Slider1 = NULL;
    ui_Slider2 = NULL;
    ui_Slider3 = NULL;
    ui_Slider4 = NULL;
    ui_Slider5 = NULL;
    ui_Slider6 = NULL;
    ui_ImgButton2 = NULL;
    ui_Delay1 = NULL;
    ui_Delay2 = NULL;
    ui_Slider8 = NULL;
    ui_Slider7 = NULL;

}
