// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SYSTEM_H
#define UI_SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_System
extern void ui_System_screen_init(void);
extern void ui_System_screen_destroy(void);
extern void ui_event_System(lv_event_t * e);
extern lv_obj_t * ui_System;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Effect4;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Effect5;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Effect1;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Effect6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_System;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

