// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Presetsmenu;
lv_obj_t * ui_ScreenPresetsMenu = NULL;
lv_obj_t * ui_PanelPresetsHeade = NULL;
lv_obj_t * ui_LabelPresetsTitle = NULL;
lv_obj_t * ui_BtnPresetsBack = NULL;
lv_obj_t * ui_uiBtnPreset1 = NULL;
lv_obj_t * ui_LabelPreset1 = NULL;
lv_obj_t * ui_uiBtnPreset2 = NULL;
lv_obj_t * ui_LabelPreset2 = NULL;
lv_obj_t * ui_uiBtnPreset3 = NULL;
lv_obj_t * ui_LabelPreset3 = NULL;
// event funtions
void ui_event_BtnPresetsBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_TitleMenuHeader, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_TitleMenuHeader_screen_init);
    }
}

void ui_event_uiBtnPreset1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_event_BtnPreset1(e);
    }
}

void ui_event_uiBtnPreset2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_event_BtnPreset2(e);
    }
}

void ui_event_uiBtnPreset3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_event_BtnPreset3(e);
    }
}

// build funtions

void ui_ScreenPresetsMenu_screen_init(void)
{
    ui_ScreenPresetsMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPresetsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPresetsMenu, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPresetsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPresetsHeade = lv_obj_create(ui_ScreenPresetsMenu);
    lv_obj_set_width(ui_PanelPresetsHeade, lv_pct(100));
    lv_obj_set_height(ui_PanelPresetsHeade, lv_pct(20));
    lv_obj_set_x(ui_PanelPresetsHeade, lv_pct(0));
    lv_obj_set_y(ui_PanelPresetsHeade, lv_pct(-40));
    lv_obj_set_align(ui_PanelPresetsHeade, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPresetsHeade, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPresetsHeade, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPresetsHeade, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPresetsHeade, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPresetsTitle = lv_label_create(ui_ScreenPresetsMenu);
    lv_obj_set_width(ui_LabelPresetsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPresetsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPresetsTitle, 0);
    lv_obj_set_y(ui_LabelPresetsTitle, -95);
    lv_obj_set_align(ui_LabelPresetsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPresetsTitle, "Presets");

    ui_BtnPresetsBack = lv_imgbtn_create(ui_ScreenPresetsMenu);
    lv_imgbtn_set_src(ui_BtnPresetsBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1618134784, NULL);
    lv_obj_set_width(ui_BtnPresetsBack, 30);
    lv_obj_set_height(ui_BtnPresetsBack, 40);
    lv_obj_set_x(ui_BtnPresetsBack, -139);
    lv_obj_set_y(ui_BtnPresetsBack, -93);
    lv_obj_set_align(ui_BtnPresetsBack, LV_ALIGN_CENTER);

    ui_uiBtnPreset1 = lv_btn_create(ui_ScreenPresetsMenu);
    lv_obj_set_width(ui_uiBtnPreset1, 320);
    lv_obj_set_height(ui_uiBtnPreset1, 50);
    lv_obj_set_x(ui_uiBtnPreset1, 0);
    lv_obj_set_y(ui_uiBtnPreset1, -45);
    lv_obj_set_align(ui_uiBtnPreset1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnPreset1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnPreset1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnPreset1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnPreset1, lv_color_hex(0xB73172), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_uiBtnPreset1, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_uiBtnPreset1, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPreset1 = lv_label_create(ui_uiBtnPreset1);
    lv_obj_set_width(ui_LabelPreset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPreset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreset1, "01A - Big Iron");

    ui_uiBtnPreset2 = lv_btn_create(ui_ScreenPresetsMenu);
    lv_obj_set_width(ui_uiBtnPreset2, 320);
    lv_obj_set_height(ui_uiBtnPreset2, 50);
    lv_obj_set_x(ui_uiBtnPreset2, 0);
    lv_obj_set_y(ui_uiBtnPreset2, 10);
    lv_obj_set_align(ui_uiBtnPreset2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnPreset2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnPreset2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnPreset2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnPreset2, lv_color_hex(0xB73172), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_uiBtnPreset2, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_uiBtnPreset2, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPreset2 = lv_label_create(ui_uiBtnPreset2);
    lv_obj_set_width(ui_LabelPreset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPreset2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreset2, "01B - El Paso");

    ui_uiBtnPreset3 = lv_btn_create(ui_ScreenPresetsMenu);
    lv_obj_set_width(ui_uiBtnPreset3, 320);
    lv_obj_set_height(ui_uiBtnPreset3, 50);
    lv_obj_set_x(ui_uiBtnPreset3, 0);
    lv_obj_set_y(ui_uiBtnPreset3, 65);
    lv_obj_set_align(ui_uiBtnPreset3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnPreset3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnPreset3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnPreset3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnPreset3, lv_color_hex(0xB73172), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_uiBtnPreset3, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_uiBtnPreset3, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_uiBtnPreset3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPreset3 = lv_label_create(ui_uiBtnPreset3);
    lv_obj_set_width(ui_LabelPreset3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreset3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPreset3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreset3, "01C - The Master's Call");

    lv_obj_add_event_cb(ui_BtnPresetsBack, ui_event_BtnPresetsBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBtnPreset1, ui_event_uiBtnPreset1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBtnPreset2, ui_event_uiBtnPreset2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBtnPreset3, ui_event_uiBtnPreset3, LV_EVENT_ALL, NULL);
    uic_Presetsmenu = ui_ScreenPresetsMenu;

}

void ui_ScreenPresetsMenu_screen_destroy(void)
{
    if(ui_ScreenPresetsMenu) lv_obj_del(ui_ScreenPresetsMenu);

    // NULL screen variables
    uic_Presetsmenu = NULL;
    ui_ScreenPresetsMenu = NULL;
    ui_PanelPresetsHeade = NULL;
    ui_LabelPresetsTitle = NULL;
    ui_BtnPresetsBack = NULL;
    ui_uiBtnPreset1 = NULL;
    ui_LabelPreset1 = NULL;
    ui_uiBtnPreset2 = NULL;
    ui_LabelPreset2 = NULL;
    ui_uiBtnPreset3 = NULL;
    ui_LabelPreset3 = NULL;

}
