// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TitleMenuHeader = NULL;
lv_obj_t * ui_BtnMenuPresets = NULL;
lv_obj_t * ui_LabelMenuPresets = NULL;
lv_obj_t * ui_BtnMenuOrder = NULL;
lv_obj_t * ui_LabelMenuOrder = NULL;
lv_obj_t * ui_BtnMenuInput = NULL;
lv_obj_t * ui_LabelMenuInput = NULL;
lv_obj_t * ui_BtnMenuOutput = NULL;
lv_obj_t * ui_LabelMenuOutput = NULL;
// event funtions
void ui_event_TitleMenuHeader(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenPresetsMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPresetsMenu_screen_init);
    }
}

void ui_event_BtnMenuPresets(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenPresetsMenu, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_ScreenPresetsMenu_screen_init);
    }
}

void ui_event_BtnMenuOrder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DifferentEffects, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_DifferentEffects_screen_init);
    }
}

void ui_event_BtnMenuInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_LabelInputTitle, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_LabelInputTitle_screen_init);
    }
}

void ui_event_BtnMenuOutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_OutputBack, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_OutputBack_screen_init);
    }
}

// build funtions

void ui_TitleMenuHeader_screen_init(void)
{
    ui_TitleMenuHeader = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TitleMenuHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TitleMenuHeader, lv_color_hex(0x101218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleMenuHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnMenuPresets = lv_btn_create(ui_TitleMenuHeader);
    lv_obj_set_width(ui_BtnMenuPresets, 320);
    lv_obj_set_height(ui_BtnMenuPresets, 50);
    lv_obj_set_x(ui_BtnMenuPresets, 0);
    lv_obj_set_y(ui_BtnMenuPresets, -85);
    lv_obj_set_align(ui_BtnMenuPresets, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenuPresets, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenuPresets, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnMenuPresets, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenuPresets, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenuPresets, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnMenuPresets, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BtnMenuPresets, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnMenuPresets, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelMenuPresets = lv_label_create(ui_BtnMenuPresets);
    lv_obj_set_width(ui_LabelMenuPresets, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMenuPresets, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMenuPresets, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenuPresets, "Presets");

    ui_BtnMenuOrder = lv_btn_create(ui_TitleMenuHeader);
    lv_obj_set_width(ui_BtnMenuOrder, 320);
    lv_obj_set_height(ui_BtnMenuOrder, 50);
    lv_obj_set_x(ui_BtnMenuOrder, 0);
    lv_obj_set_y(ui_BtnMenuOrder, -30);
    lv_obj_set_align(ui_BtnMenuOrder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenuOrder, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenuOrder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnMenuOrder, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenuOrder, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenuOrder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnMenuOrder, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BtnMenuOrder, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnMenuOrder, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelMenuOrder = lv_label_create(ui_BtnMenuOrder);
    lv_obj_set_width(ui_LabelMenuOrder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMenuOrder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMenuOrder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenuOrder, "Order of Signal-chain");

    ui_BtnMenuInput = lv_btn_create(ui_TitleMenuHeader);
    lv_obj_set_width(ui_BtnMenuInput, 320);
    lv_obj_set_height(ui_BtnMenuInput, 50);
    lv_obj_set_x(ui_BtnMenuInput, 0);
    lv_obj_set_y(ui_BtnMenuInput, 25);
    lv_obj_set_align(ui_BtnMenuInput, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenuInput, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenuInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnMenuInput, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenuInput, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenuInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnMenuInput, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BtnMenuInput, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnMenuInput, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelMenuInput = lv_label_create(ui_BtnMenuInput);
    lv_obj_set_width(ui_LabelMenuInput, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMenuInput, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMenuInput, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenuInput, "Input Gain");

    ui_BtnMenuOutput = lv_btn_create(ui_TitleMenuHeader);
    lv_obj_set_width(ui_BtnMenuOutput, 320);
    lv_obj_set_height(ui_BtnMenuOutput, 50);
    lv_obj_set_x(ui_BtnMenuOutput, 0);
    lv_obj_set_y(ui_BtnMenuOutput, 80);
    lv_obj_set_align(ui_BtnMenuOutput, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenuOutput, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenuOutput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnMenuOutput, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenuOutput, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenuOutput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnMenuOutput, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BtnMenuOutput, lv_color_hex(0x1707BF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnMenuOutput, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelMenuOutput = lv_label_create(ui_BtnMenuOutput);
    lv_obj_set_width(ui_LabelMenuOutput, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMenuOutput, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMenuOutput, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenuOutput, "Output Level");

    lv_obj_add_event_cb(ui_BtnMenuPresets, ui_event_BtnMenuPresets, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenuOrder, ui_event_BtnMenuOrder, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenuInput, ui_event_BtnMenuInput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenuOutput, ui_event_BtnMenuOutput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TitleMenuHeader, ui_event_TitleMenuHeader, LV_EVENT_ALL, NULL);

}

void ui_TitleMenuHeader_screen_destroy(void)
{
    if(ui_TitleMenuHeader) lv_obj_del(ui_TitleMenuHeader);

    // NULL screen variables
    ui_TitleMenuHeader = NULL;
    ui_BtnMenuPresets = NULL;
    ui_LabelMenuPresets = NULL;
    ui_BtnMenuOrder = NULL;
    ui_LabelMenuOrder = NULL;
    ui_BtnMenuInput = NULL;
    ui_LabelMenuInput = NULL;
    ui_BtnMenuOutput = NULL;
    ui_LabelMenuOutput = NULL;

}
