// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TITLEMENUHEADER_H
#define UI_TITLEMENUHEADER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TitleMenuHeader
extern void ui_TitleMenuHeader_screen_init(void);
extern void ui_TitleMenuHeader_screen_destroy(void);
extern void ui_event_TitleMenuHeader(lv_event_t * e);
extern lv_obj_t * ui_TitleMenuHeader;
extern void ui_event_BtnMenuPresets(lv_event_t * e);
extern lv_obj_t * ui_BtnMenuPresets;
extern lv_obj_t * ui_LabelMenuPresets;
extern void ui_event_BtnMenuOrder(lv_event_t * e);
extern lv_obj_t * ui_BtnMenuOrder;
extern lv_obj_t * ui_LabelMenuOrder;
extern void ui_event_BtnMenuInput(lv_event_t * e);
extern lv_obj_t * ui_BtnMenuInput;
extern lv_obj_t * ui_LabelMenuInput;
extern void ui_event_BtnMenuOutput(lv_event_t * e);
extern lv_obj_t * ui_BtnMenuOutput;
extern lv_obj_t * ui_LabelMenuOutput;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

